# This workflow will build a golang project

name: Integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * *'

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    env:
      PINECONE_API_KEY: ${{ secrets.PINECONE_